name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for tags
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run release
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          npm run release
      - name: Configure Git for pushing with token
        run: git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/somduttasinha/poker-tracker.git
      - name: Push release
        run: git push --follow-tags origin main
